import { useState } from 'react';
import { t } from '../../i18n/i18n';
import { useUserStore } from '../../state/userStore';
import type { ExecutiveSnapshot } from '../../types';
import { ExportImportDialog } from './ExportImportDialog';

interface Props {
  onClose: () => void;
}

export function SnapshotPanel({ onClose }: Props) {
  const { snapshots, deleteSnapshot } = useUserStore();
  const [showEI, setShowEI] = useState(false);

  const handleExportMarkdown = (snap: ExecutiveSnapshot) => {
    const md = `# OrbitIQ Executive Snapshot
Generated: ${new Date(snap.timestamp).toLocaleString()}

## Context
- **Source Mode**: ${snap.sourceMode}
- **Visible Count**: ${snap.visibleCount.toLocaleString()}
- **Most Crowded Band**: ${snap.mostCrowdedBand}
- **Dominant Group**: ${snap.dominantGroup}
- **Highest Region Concentration**: ${snap.highestConcentrationRegion}

${snap.selectedSatellite ? `## Selected Target\n- **Name**: ${snap.selectedSatellite.name}\n- **NORAD**: ${snap.selectedSatellite.satnum}\n- **Alt**: ${Math.round(snap.selectedSatellite.alt)} km\n\n` : ''}
${snap.executiveBrief ? `## Executive Summary\n${snap.executiveBrief.headline}\n\n${snap.executiveBrief.sections.map(s => `### ${s.title}\n${s.body}`).join('\n\n')}\n\n` : ''}
${snap.missionBrief ? `## Mission Scenario: ${snap.missionBrief.title}\n${snap.missionBrief.insight}\n\n` : ''}
${snap.riskLayerSummary ? `## Risk Signal: ${snap.riskLayerSummary.category}\n**Score**: ${snap.riskLayerSummary.score} (${snap.riskLayerSummary.level})\n${snap.riskLayerSummary.explanation}\n\n` : ''}
## Caveats
${snap.caveats.map(c => `- ${c}`).join('\n')}

---
*Generated by OrbitIQ Command Center*
`;
    
    navigator.clipboard.writeText(md).then(() => {
      alert(t('markdown_copied') || 'Markdown copied to clipboard!');
    }).catch(err => {
      console.error('Failed to copy markdown:', err);
      alert('Failed to copy markdown. See console.');
    });
  };

  return (
    <aside className="left-panel snapshot-panel glass">
      <div className="panel-header">
        <h2>{t('executive_snapshots') || 'Executive Snapshots'}</h2>
        <button className="panel-close" onClick={onClose} aria-label="Close">×</button>
      </div>

      <div className="panel-body">
        {snapshots.length === 0 ? (
          <div className="panel-empty">{t('no_snapshots') || 'No snapshots saved.'}</div>
        ) : (
          <div className="snapshot-list">
            {snapshots.map(s => (
              <div key={s.id} className="snapshot-card">
                <div className="s-header">
                  <div className="s-date">{new Date(s.timestamp).toLocaleString()}</div>
                  <button 
                    className="s-remove" 
                    onClick={() => deleteSnapshot(s.id)}
                    title={t('delete') || 'Delete'}
                  >
                    ✕
                  </button>
                </div>
                <div className="s-body">
                  <p><strong>Total:</strong> {s.visibleCount.toLocaleString()} objects</p>
                  <p><strong>Hotspot:</strong> {s.highestConcentrationRegion}</p>
                </div>
                <div className="s-actions">
                  <button className="export-md-btn" onClick={() => handleExportMarkdown(s)}>
                    {t('export_markdown') || 'Copy Markdown'}
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
      
      <div className="panel-footer">
        <button className="ei-toggle-btn" onClick={() => setShowEI(true)}>
          {t('export_import') || 'Export / Import Data'}
        </button>
        <small style={{display: 'block', marginTop: '10px'}}>{t('local_storage_note') || 'Saved locally in this browser. Only public metadata stored.'}</small>
      </div>

      {showEI && <ExportImportDialog onClose={() => setShowEI(false)} />}
    </aside>
  );
}
