import type { ExecutiveBrief, ExecutiveSnapshot } from '../types';

interface BriefMarkdownParams {
  brief: ExecutiveBrief;
  generatedAt: number;
  sourceMode: string;
  totalLoaded: number;
  visibleCount: number;
  mostCrowdedBand: string;
  highestConcentrationRegion: string;
  dominantGroup: string;
  congestionScore: number;
  congestionLevel: string;
  caveats: string[];
}

export function buildExecutiveBriefMarkdown(params: BriefMarkdownParams): string {
  const {
    brief,
    generatedAt,
    sourceMode,
    totalLoaded,
    visibleCount,
    mostCrowdedBand,
    highestConcentrationRegion,
    dominantGroup,
    congestionScore,
    congestionLevel,
    caveats,
  } = params;

  return `# OrbitIQ Executive Orbital Brief
Generated: ${new Date(generatedAt).toLocaleString()}

## Summary
${brief.headline}

## Context
- Source Mode: ${sourceMode}
- Total Loaded: ${totalLoaded.toLocaleString()}
- Visible Count: ${visibleCount.toLocaleString()}
- Most Crowded Band: ${mostCrowdedBand}
- Highest Region Concentration: ${highestConcentrationRegion}
- Dominant Group: ${dominantGroup}
- Congestion: ${congestionScore}/100 (${congestionLevel})

${brief.sections.map((section) => `## ${section.title}\n${section.body}`).join('\n\n')}

## Caveats
${caveats.map((caveat) => `- ${caveat}`).join('\n')}

---
Generated by OrbitIQ Command Center
`;
}

export function buildExecutiveSnapshotMarkdown(snap: ExecutiveSnapshot): string {
  return `# OrbitIQ Executive Snapshot
Generated: ${new Date(snap.timestamp).toLocaleString()}

## Context
- Source Mode: ${snap.sourceMode}
- Total Loaded: ${snap.totalLoaded.toLocaleString()}
- Visible Count: ${snap.visibleCount.toLocaleString()}
- Most Crowded Band: ${snap.mostCrowdedBand}
- Dominant Group: ${snap.dominantGroup}
- Highest Region Concentration: ${snap.highestConcentrationRegion}

${snap.selectedSatellite ? `## Selected Target\n- Name: ${snap.selectedSatellite.name}\n- NORAD: ${snap.selectedSatellite.satnum}\n- Altitude: ${Math.round(snap.selectedSatellite.alt)} km\n- Subpoint: ${snap.selectedSatellite.lat.toFixed(2)}, ${snap.selectedSatellite.lon.toFixed(2)}\n\n` : ''}
${snap.executiveBrief ? `## Executive Summary\n${snap.executiveBrief.headline}\n\n${snap.executiveBrief.sections.map((s) => `### ${s.title}\n${s.body}`).join('\n\n')}\n\n` : ''}
${snap.missionBrief ? `## Mission Scenario: ${snap.missionBrief.title}\n${snap.missionBrief.insight}\n\n` : ''}
${snap.riskLayerSummary ? `## Risk Signal: ${snap.riskLayerSummary.category}\nScore: ${snap.riskLayerSummary.score}/100 (${snap.riskLayerSummary.level})\n${snap.riskLayerSummary.explanation}\n\n` : ''}
## Caveats
${snap.caveats.map((c) => `- ${c}`).join('\n')}

---
Generated by OrbitIQ Command Center
`;
}
